# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170509_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='cidade teste', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(default='complemento teste', max_length=100, verbose_name='Complemento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='pais teste', max_length=10, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(default='teste teste', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=123, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default=1234567, max_length=8, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='sp', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='rua teste', max_length=100, verbose_name='Rua'),
            preserve_default=False,
        ),
    ]
