# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=300, verbose_name='Peso'),
            preserve_default=False,
        ),
    ]
